### PR TITLE
Port to python3

### PR DESCRIPTION
**Pull request by Wenzel**
This is an attempt to make this repo Python 3 compatible.

I just ran `futurize` over the `setup.py` and that was enough, capstone already supports Python3.

I'm not familiar with the procedure, or naming convention for `Pypi`.

Please let me know if i have to increase the version number somewhere.

### CODE REVIEW

**Comment by Wenzel** [comment]
What i did

~~~
python setup.py sdist
python setup.py build
python setup.py install
~~~

**Comment by Wenzel** [comment]
Actually, this python3 is not working properly.

After the installation, when you try to `import capstone`, python complains that i cannot load the library.
~~~Python
python -c 'import capstone'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/lol/venv/lib/python3.5/site-packages/rekall_capstone-3.0.4.post2-py3.5-linux-x86_64.egg/capstone/__init__.py", line 250, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
~~~

**Comment by scudette** [comment]
I think the bug is:

```
  ext_modules=[
        Extension(
            "libcapstone",
            get_sources(),
```

It just puts the libcapstone one directory too deep.

You will need to first build an sdist then install with pip:
```
pip install -I dist/rekall-capstone-3.0.4.post2.tar.gz 
```

I am not sure if installing with setup.py will put things in the right places (and this is not what is happening when pip installs it as a rekall dependency anyway).

If this works, maybe up the version too (from post2 to post3).

**Comment by Wenzel** [comment]
Thanks for your reply,

building it as an `sdist` and installing it with `pip install -I` makes it work.

I updated the version number, to `rekall-capstone-3.0.4.post3` as you requested.

**Pull request merged**
